# Generated by Django 5.0.1 on 2024-01-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerbloom', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=2234, max_digits=10, verbose_name='Delivery Charge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_info',
            field=models.TextField(default=2234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.TextField(default=2234),
            preserve_default=False,
        ),
    ]
